### ISSUE TITLE
Practica operaciones

### ISSUE THREAD

**Issue by Felix-Angel** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Felix-Angel#1]
[PRACTICA 1_MATEDISCRETAS_FELIX.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-Felix-Angel/files/12564549/PRACTICA.1_MATEDISCRETAS_FELIX.pdf)

**Comment by 23620031** [comment]
PORTADA 25/25
PROCEDIMIENTO 25/25
FIGURAS ILUSTRACIONES Y FOTOGRAFÍAS 25/25
RESULTADOS Y CONCLUSIONES 25/25

CALIFICACIÓN 20/20

CALIFICADO POR EQUIPO DE "LÓPEZ DOMÍNGUEZ ISAÍAS BRAYAN"

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
